In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Numpy Generation methods

In [9]:
arr = np.arange(0,11,2)

In [10]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr = np.zeros(3)

In [14]:
arr

array([0., 0., 0.])

In [15]:
arr = np.ones(3)

In [16]:
arr

array([1., 1., 1.])

In [18]:
arr = np.zeros((3,4))

In [19]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
arr = np.ones((3,4))

In [21]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
# linspace takes the third argument which is actually the
# number of points expected instead of stepsizes in case of np.arange

In [23]:
arr = np.linspace(0,11,5)

In [24]:
arr

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [25]:
# random numbers

In [26]:
# uniform distribution
np.random.rand(5)

array([0.8555614 , 0.39882512, 0.95443812, 0.88712277, 0.51405856])

In [27]:
np.random.rand(5,5)

array([[0.33624809, 0.82442831, 0.27195851, 0.74964748, 0.31294742],
       [0.60689176, 0.18211254, 0.03695451, 0.83242337, 0.64135789],
       [0.67479372, 0.5480111 , 0.10823612, 0.22728259, 0.0075099 ],
       [0.17446769, 0.713255  , 0.07643438, 0.19282708, 0.15457027],
       [0.11167925, 0.07006693, 0.26161185, 0.62938517, 0.66248209]])

In [28]:
# for normal distribution centered around zero

In [29]:
np.random.rand()

0.8353812170669156

In [32]:
np.random.randint(1,100,4)

array([90,  3, 11, 10])

In [33]:
arr

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [34]:
arr = np.linspace(0,11,10)

In [35]:
arr

array([ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889,
        6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ])

In [36]:
arr.reshape(2,5)

array([[ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889],
       [ 6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ]])

In [40]:
arr = arr.reshape(5,2)

In [41]:
arr.shape

(5, 2)

In [42]:
arr.dtype

dtype('float64')